swagger: "2.0"
info:
  description: "Placeholder"
  version: "1.0.0"
  title: "Assignment2-Microserviece(Course)"
 
host: "petstore.swagger.io"
basePath: "/v2"

tags:

  
 
- name: "Course"
  description: "Everything about a course"


  
paths:
 
  /Course:
    post:
      tags:
      - "Course"
      summary: "Create a course"
      description: ""
      operationId: "CreateCourse"
      consumes:
      - "application/json"
      - "application/xml"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - in : "body"
        name: "Course"
        description: "Create a course"
        required: true
        schema:
          $ref: "#/definitions/Course"
      responses:
        "200":
          description: "OK"
    put:
      tags:
      - "Course"
      summary: "Updates a course at ITU"
      description: ""
      operationId: "UpdateCourse"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Course that needs to be updated"
        required: false
        schema:
          $ref: "#/definitions/Course"
      responses:
        "200":
          description: "OK"
    get:
      tags:
      - "Course"
      summary: " Returns all courses"
      operationId: "GetAllCourses"
      produces:
      - "application/xml"
      - "application/json"
      responses:
        "200":
          description: "OK"
            
          
          
  /Course/Students:
    get:
      tags:
      - "Course"
      summary: " Returns all students attending a course"
      operationId: "GetAllStudents"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - name: "Course ID"
        in: "query"
        type: "integer"
        format: "int64"
        required: true
        
      responses:
       "200":
        description: "successful operation"
        schema:
          type: "object"
          additionalProperties:
            type: "object"
            properties:
              id:
                type: "string"
              firstname:
                type: "string"
              lastName:
                type: "string"
              Email:
                type: "string"
  
  /Course/{id}:
    get:
      tags:
      - "Course"
      summary: "Find course by ID"
      description: "Returns a single course"
      operationId: "GetCourseByID"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - name: "id"
        in: "path"
        description: "ID of course to return"
        required: true
        type: "string"
      responses:
        "200":
          description: "successful operation"
    delete:
      tags:
      - "Course"
      summary: "Deletes a course"
      description: ""
      operationId: "deleteCourse"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - name: "id"
        in: "path"
        description: "Course id to delete"
        required: true
        type: "string"
      responses:
        "200":
          description: "OK"
 
          
      
definitions:
  Course:
    type: "object"
    properties:
      id:
        type: "string"
      coursename:
        type: "string"
      courseTeacher:
        type: "object"
      Workload(ETCS):
        type: "number"
      SatificationRatingByAllStudentsAttendingCourse:
        type: "number"
        
        
        
        
    



 
  
